feign:
  sentinel:
    enabled: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.miaosha.miaoshaproduct.domain.entity
server:
  port: 8090
spring:
  application:
    name: miaosha-user
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
    sentinel:
      datasource:
        ds1:
          nacos:
            data-id: miaosha-sentinel
            data-type: json
            group-id: DEFAULT_GROUP
            rule-type: flow
            server-addr: localhost:8848
      transport:
        dashboard: localhost:8082
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      initial-size: 10
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      password: root
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      validation-query: SELECT 'x'
    name: miaosha-user
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        max-wait: 6000ms
        min-idle: 4
    password: 123456
    port: 6379
