server:
  port: 8099
spring:
  application:
    name: miaosha-getway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-getway-provider
          uri: lb://miaosha-user
          predicates:
            - Path=/user/**
