server:
  port: 8099
spring:
  application:
    name: miaosha-getway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: getway-miaosha-user
          uri: lb://miaosha-user
          predicates:
            - Path=/user/**
        - id: getway-miaosha-order
            uri: lb://miaosha-order
            predicates:
              - Path=/order/**
        - id: getway-miaosha-product
            uri: lb://miaosha-product
            predicates:
              - Path=/product/**
